name: PDP BIN Check

on:
  workflow_dispatch:

jobs:
  check-pdp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run PDP Checker
        run: node checkPdpPages.js all

      - name: Create results folder
        run: mkdir -p results

      - name: Move generated files
        run: |
          mv pdpCheckResults*.json results/ || true

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: pdp-check-results
          path: results/
